name: Push to Neocities
on: [push]
jobs:
  Push to Neocities:
    runs-on: ubuntu-latest
    steps:
      - run: echo "installing neocities CLI"
      - run: gem install neocities
      - run: echo "uploading files to Neocities"
      - run: echo "michaelpitts\n$NEOCITIES_TOKEN" | neocities push -e .github/* .