name: Push to Neocities
run-name: ${{ github.actor }} is updating michaelcpitts.com
on: [push]
jobs:
  Push-to-Neocities:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      # - run: echo "update OS"
      # - run: sudo apt-get -y update; sudo apt-get -y upgrade
      - run: echo "installing neocities CLI"
      # - run: sudo apt-get -y install ruby-full
      - run: sudo gem install neocities -f 
      - run: echo "uploading files to Neocities"
      - run: chmod +x ./upload.bash
      - run: bash ./upload.bash
