name: Push to Neocities
run-name: ${{ github.actor }} is updating michaelcpitts.com
on: [push]
jobs:
  Push-to-Neocities:
    runs-on: ubuntu-latest
    steps:
      - run: echo "installing neocities CLI"
      - run: sudo apt-get -y install ruby-full
      - run: sudo gem install neocities
      - run: echo "uploading files to Neocities"
      - run: echo "michaelpitts\n$NEOCITIES_TOKEN" | neocities push -e .github/* .
